// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Stellmart.Context;
using System;

namespace Stellmart.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Stellmart.Api.Context.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Stellmart.Api.Context.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<bool>("Flagged");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<bool>("ManagedAccount");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<bool>("MustRecoverKey");

                    b.Property<bool>("MustResetKey");

                    b.Property<int>("NativeCurrencyId");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<int>("PrimaryShippingLocationId");

                    b.Property<int>("RewardsLevelId");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("StellarEncryptedSecretKey");

                    b.Property<string>("StellarPublicKey");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<int>("TwoFactorTypeId");

                    b.Property<Guid>("UniqueId");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<int>("VerificationLevelId");

                    b.HasKey("Id");

                    b.HasIndex("NativeCurrencyId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PrimaryShippingLocationId");

                    b.HasIndex("RewardsLevelId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("DistanceUnitId");

                    b.Property<int>("DistanceUnitTypeId");

                    b.Property<int>("GeoLocationId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<double>("Radius");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("DistanceUnitId");

                    b.HasIndex("GeoLocationId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContractStateId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CurrentSequenceNumber");

                    b.Property<string>("EscrowAccountId")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("ContractStateId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ContractPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<bool>("Contested");

                    b.Property<int>("ContractId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("SequenceNumber");

                    b.Property<int>("TimeDelay");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractPhases");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.CurrencyAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CurrencyTypeId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyTypeId");

                    b.ToTable("CurrencyAmounts");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.DeliveryRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("DestinationId");

                    b.Property<bool>("Fulfilled");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("RequestorId");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("RequestorId");

                    b.ToTable("DeliveryRequest");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.GeoLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.ToTable("GeoLocations");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConditionId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Descriptors");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("SKU");

                    b.Property<int>("TradeInStateId");

                    b.Property<int>("TradeInValueId");

                    b.Property<string>("UPC");

                    b.Property<Guid>("UniqueId");

                    b.Property<int>("UnitPriceId");

                    b.Property<int>("UnitTypeId");

                    b.Property<int>("UnitsAvailable");

                    b.Property<int>("UnitsReturned");

                    b.Property<int>("UnitsSold");

                    b.HasKey("Id");

                    b.HasIndex("TradeInStateId");

                    b.HasIndex("TradeInValueId");

                    b.HasIndex("UnitPriceId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.LineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("InventoryItemId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("Quantity");

                    b.Property<int?>("ShippingManifestId");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("LineItems");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<bool>("Flagged");

                    b.Property<bool>("Internal");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("ItemMetaDataId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("ServiceId");

                    b.Property<int?>("ThreadId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("ItemMetaDataId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ThreadId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ListingInventoryItem", b =>
                {
                    b.Property<int>("ListingId");

                    b.Property<int>("InventoryItemId");

                    b.HasKey("ListingId", "InventoryItemId");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("ListingInventoryItems");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("MessageThreadId");

                    b.Property<DateTime>("PostedOn");

                    b.Property<int>("PosterId");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("MessageThreadId");

                    b.HasIndex("PosterId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.MessageThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("InitiatorId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorId");

                    b.ToTable("MessageThreads");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.OnlineStoreReview", b =>
                {
                    b.Property<int>("OnlineStoreId");

                    b.Property<int>("ReviewId");

                    b.HasKey("OnlineStoreId", "ReviewId");

                    b.HasIndex("ReviewId");

                    b.ToTable("OnlineStoreReviews");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.PreTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContractPhaseId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("MaximumTime");

                    b.Property<DateTime>("MinimumTime");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("PreTransactionTypeId");

                    b.Property<bool>("Submitted");

                    b.Property<Guid>("UniqueId");

                    b.Property<string>("XdrString");

                    b.HasKey("Id");

                    b.HasIndex("ContractPhaseId");

                    b.HasIndex("PreTransactionTypeId");

                    b.ToTable("PreTransactions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PreTransaction");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.PricePerDistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrencyAmountId");

                    b.Property<int>("DistanceUnitId");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyAmountId");

                    b.HasIndex("DistanceUnitId");

                    b.ToTable("PricePerDistances");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.PricePerTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrencyAmountId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("TimeUnitId");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyAmountId");

                    b.HasIndex("TimeUnitId");

                    b.ToTable("PricePerTimes");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ProductShipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContractId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DeliveredOn");

                    b.Property<int>("DeliveryRequestId");

                    b.Property<bool>("FulfilledInternally");

                    b.Property<int>("FulfillmentStateId");

                    b.Property<bool>("Internal");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int>("ReceiverId");

                    b.Property<int>("SenderId");

                    b.Property<DateTime>("ShippedOn");

                    b.Property<int>("ShippingCarrierId");

                    b.Property<int>("ShippingManifestId");

                    b.Property<bool>("TradeIn");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("DeliveryRequestId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("ShippingCarrierId");

                    b.HasIndex("ShippingManifestId");

                    b.ToTable("ProductShipments");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.ContractState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("ContractStates");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.ContractType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("ContractTypes");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.DistanceUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("DistanceUnits");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.FulfillmentState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("FulfillmentStates");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.ItemCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("ItemConditions");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.ListingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("SubCategoryId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("ListingCategory");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.PreTransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("PreTransactionType");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.QuantityUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("QuantityUnits");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.RewardsLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("RewardsLevels");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.ShippingCarrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("ShippingCarriers");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("SuperCategoryId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.SuperCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("SuperCategories");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.TimeUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("TimeUnits");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.TradeInState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("TradeInStates");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.TwoFactorAuthenticationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.ToTable("TwoFactorAuthenticationTypes");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.VerificationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int?>("ApplicationUserId");

                    b.Property<string>("Description");

                    b.Property<int>("DisplayOrder");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("VerificationLevels");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("LocationId");

                    b.Property<string>("Name");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("ReviewerId");

                    b.Property<int>("Stars");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<int>("NativeCurrencyId");

                    b.Property<string>("TagLine");

                    b.Property<Guid>("UniqueId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Service");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Service");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ServiceRequestFulfillment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContractId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("FulfillmentStateId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("ServiceId");

                    b.Property<int>("ServiceRequestId");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("FulfillmentStateId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("ServiceRequestFulfillment");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ShippingManifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.ToTable("ShippingManifests");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ShippingManifestLineItem", b =>
                {
                    b.Property<int>("ShippingManifestId");

                    b.Property<int>("LineItemId");

                    b.HasKey("ShippingManifestId", "LineItemId");

                    b.HasIndex("LineItemId");

                    b.ToTable("ShippingManifestLineItems");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("PreTransactionId");

                    b.Property<bool>("Signed");

                    b.Property<DateTime>("SignedOn");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("PreTransactionId");

                    b.ToTable("Signature");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Signature");
                });

            modelBuilder.Entity("Stellmart.Api.Context.ItemMetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("KeyWords");

                    b.Property<int>("ListingCategoryId");

                    b.Property<int>("SubCategoryId");

                    b.Property<int>("SuperCategoryId");

                    b.Property<Guid>("UniqueId");

                    b.Property<int>("itemConditionId");

                    b.HasKey("Id");

                    b.HasIndex("ListingCategoryId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("SuperCategoryId");

                    b.HasIndex("itemConditionId");

                    b.ToTable("ItemMetaDatas");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int>("GeoLocationId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LocationComponents");

                    b.Property<string>("PlaceId");

                    b.Property<Guid>("UniqueId");

                    b.Property<bool>("Verified");

                    b.HasKey("Id");

                    b.HasIndex("GeoLocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Stellmart.Api.Context.TradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("ItemMetaDataId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("OwnerId");

                    b.Property<string>("Title");

                    b.Property<int>("TradeInStateId");

                    b.Property<int>("TradeInValueId");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("ItemMetaDataId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TradeInStateId");

                    b.HasIndex("TradeInValueId");

                    b.ToTable("TradeItems");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.DisputeTransaction", b =>
                {
                    b.HasBaseType("Stellmart.Api.Context.Entities.PreTransaction");


                    b.ToTable("DisputeTransaction");

                    b.HasDiscriminator().HasValue("DisputeTransaction");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.DeliveryService", b =>
                {
                    b.HasBaseType("Stellmart.Api.Context.Entities.Service");

                    b.Property<int?>("ApplicationUserId");

                    b.Property<int>("ServiceAreaId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ServiceAreaId");

                    b.ToTable("DeliveryService");

                    b.HasDiscriminator().HasValue("DeliveryService");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.DistributionCenter", b =>
                {
                    b.HasBaseType("Stellmart.Api.Context.Entities.Service");

                    b.Property<bool>("Internal");

                    b.ToTable("DistributionCenter");

                    b.HasDiscriminator().HasValue("DistributionCenter");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.OnlineStore", b =>
                {
                    b.HasBaseType("Stellmart.Api.Context.Entities.Service");

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnName("OnlineStore_ApplicationUserId");

                    b.Property<bool>("Global");

                    b.Property<int>("ItemMetaDateId");

                    b.Property<int>("LocationId");

                    b.Property<int>("ServiceRegionId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ServiceRegionId");

                    b.ToTable("OnlineStore");

                    b.HasDiscriminator().HasValue("OnlineStore");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.OracleSignature", b =>
                {
                    b.HasBaseType("Stellmart.Api.Context.Entities.Signature");

                    b.Property<string>("OracleId")
                        .IsRequired();

                    b.ToTable("OracleSignature");

                    b.HasDiscriminator().HasValue("OracleSignature");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.SystemSignature", b =>
                {
                    b.HasBaseType("Stellmart.Api.Context.Entities.Signature");


                    b.ToTable("SystemSignature");

                    b.HasDiscriminator().HasValue("SystemSignature");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.UserSignature", b =>
                {
                    b.HasBaseType("Stellmart.Api.Context.Entities.Signature");

                    b.Property<int>("SignerId");

                    b.ToTable("UserSignature");

                    b.HasDiscriminator().HasValue("UserSignature");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Stellmart.Api.Context.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Stellmart.Api.Context.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Stellmart.Api.Context.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Stellmart.Api.Context.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Stellmart.Api.Context.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.ApplicationUser", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.Currency", "NativeCurrency")
                        .WithMany()
                        .HasForeignKey("NativeCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Location", "PrimaryShippingLocation")
                        .WithMany()
                        .HasForeignKey("PrimaryShippingLocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.RewardsLevel", "RewardsLevel")
                        .WithMany()
                        .HasForeignKey("RewardsLevelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Area", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.DistanceUnit", "DistanceUnit")
                        .WithMany()
                        .HasForeignKey("DistanceUnitId");

                    b.HasOne("Stellmart.Api.Context.Entities.GeoLocation", "GeoLocation")
                        .WithMany()
                        .HasForeignKey("GeoLocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Contract", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.ContractState", "State")
                        .WithMany()
                        .HasForeignKey("ContractStateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ContractPhase", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.Contract", "Contract")
                        .WithMany("Phases")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.CurrencyAmount", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.Currency", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.DeliveryRequest", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Location", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.ApplicationUser", "Requestor")
                        .WithMany()
                        .HasForeignKey("RequestorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.InventoryItem", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.TradeInState", "TradeInState")
                        .WithMany()
                        .HasForeignKey("TradeInStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.CurrencyAmount", "TradeInValue")
                        .WithMany()
                        .HasForeignKey("TradeInValueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.CurrencyAmount", "Price")
                        .WithMany()
                        .HasForeignKey("UnitPriceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.QuantityUnit", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.LineItem", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Listing", b =>
                {
                    b.HasOne("Stellmart.Api.Context.ItemMetaData", "ItemMetaData")
                        .WithMany()
                        .HasForeignKey("ItemMetaDataId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.OnlineStore", "Store")
                        .WithMany("Listings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.MessageThread", "Thread")
                        .WithMany()
                        .HasForeignKey("ThreadId");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ListingInventoryItem", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.InventoryItem", "InventoryItem")
                        .WithMany("ListingInventoryItems")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.Listing", "Listing")
                        .WithMany("ListingInventoryItems")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Message", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.MessageThread", "MessageThread")
                        .WithMany()
                        .HasForeignKey("MessageThreadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.ApplicationUser", "Poster")
                        .WithMany()
                        .HasForeignKey("PosterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.MessageThread", b =>
                {
                    b.HasOne("Stellmart.Api.Context.ApplicationUser", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.OnlineStoreReview", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.OnlineStore", "OnlineStore")
                        .WithMany("OnlineStoreReviews")
                        .HasForeignKey("OnlineStoreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.Review", "Review")
                        .WithMany("OnlineStoreReviews")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.PreTransaction", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.ContractPhase", "Phase")
                        .WithMany("Transactions")
                        .HasForeignKey("ContractPhaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.PreTransactionType", "PreTransactionType")
                        .WithMany()
                        .HasForeignKey("PreTransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.PricePerDistance", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.CurrencyAmount", "Amount")
                        .WithMany()
                        .HasForeignKey("CurrencyAmountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.DistanceUnit", "DistanceUnit")
                        .WithMany()
                        .HasForeignKey("DistanceUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.PricePerTime", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.CurrencyAmount", "Amount")
                        .WithMany()
                        .HasForeignKey("CurrencyAmountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.TimeUnit", "TimeUnit")
                        .WithMany()
                        .HasForeignKey("TimeUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ProductShipment", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.DeliveryRequest", "DeliveryRequest")
                        .WithMany()
                        .HasForeignKey("DeliveryRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.ShippingCarrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("ShippingCarrierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ShippingManifest", "Manifest")
                        .WithMany()
                        .HasForeignKey("ShippingManifestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ReadOnly.VerificationLevel", b =>
                {
                    b.HasOne("Stellmart.Api.Context.ApplicationUser")
                        .WithMany("VerificationLevels")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Region", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Review", b =>
                {
                    b.HasOne("Stellmart.Api.Context.ApplicationUser", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ServiceRequestFulfillment", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.Service", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.FulfillmentState", "FulfillmentState")
                        .WithMany()
                        .HasForeignKey("FulfillmentStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.Service", "ServiceRequest")
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.ShippingManifestLineItem", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.LineItem", "LineItem")
                        .WithMany("ShippingManifestLineItems")
                        .HasForeignKey("LineItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ShippingManifest", "Manifest")
                        .WithMany("ShippingManifestLineItems")
                        .HasForeignKey("ShippingManifestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.Signature", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.PreTransaction", "Transaction")
                        .WithMany("Signatures")
                        .HasForeignKey("PreTransactionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.ItemMetaData", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.ListingCategory", "ListingCategory")
                        .WithMany()
                        .HasForeignKey("ListingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.SuperCategory", "SuperCategory")
                        .WithMany()
                        .HasForeignKey("SuperCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.ItemCondition", "ItemCondition")
                        .WithMany()
                        .HasForeignKey("itemConditionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Location", b =>
                {
                    b.HasOne("Stellmart.Api.Context.Entities.GeoLocation", "GeoLocation")
                        .WithMany()
                        .HasForeignKey("GeoLocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.TradeItem", b =>
                {
                    b.HasOne("Stellmart.Api.Context.ItemMetaData", "ItemMetaData")
                        .WithMany()
                        .HasForeignKey("ItemMetaDataId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.ApplicationUser", "Owner")
                        .WithMany("TradeItems")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.ReadOnly.TradeInState", "TradeInState")
                        .WithMany()
                        .HasForeignKey("TradeInStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.CurrencyAmount", "TradeInValue")
                        .WithMany()
                        .HasForeignKey("TradeInValueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.DeliveryService", b =>
                {
                    b.HasOne("Stellmart.Api.Context.ApplicationUser")
                        .WithMany("DeliveryServices")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Stellmart.Api.Context.Entities.Area", "ServiceArea")
                        .WithMany()
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stellmart.Api.Context.Entities.OnlineStore", b =>
                {
                    b.HasOne("Stellmart.Api.Context.ApplicationUser")
                        .WithMany("OnlineStores")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Stellmart.Api.Context.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stellmart.Api.Context.Entities.Region", "ServiceRegion")
                        .WithMany()
                        .HasForeignKey("ServiceRegionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
